/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HeartNote = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'position' : IDL.Tuple(IDL.Float64, IDL.Float64),
});

export const idlService = IDL.Service({
  'addHeartNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Tuple(IDL.Float64, IDL.Float64),
      ],
      [],
      [],
    ),
  'deleteHeartNote' : IDL.Func([IDL.Text], [], []),
  'editHeartNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllHeartNotes' : IDL.Func([], [IDL.Vec(HeartNote)], ['query']),
  'getHeartNote' : IDL.Func([IDL.Text], [HeartNote], ['query']),
  'getPersonalGreetingMessage' : IDL.Func([], [IDL.Text], ['query']),
  'updatePersonalGreetingMessage' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HeartNote = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'position' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  
  return IDL.Service({
    'addHeartNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Tuple(IDL.Float64, IDL.Float64),
        ],
        [],
        [],
      ),
    'deleteHeartNote' : IDL.Func([IDL.Text], [], []),
    'editHeartNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllHeartNotes' : IDL.Func([], [IDL.Vec(HeartNote)], ['query']),
    'getHeartNote' : IDL.Func([IDL.Text], [HeartNote], ['query']),
    'getPersonalGreetingMessage' : IDL.Func([], [IDL.Text], ['query']),
    'updatePersonalGreetingMessage' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };