/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HeartNote {
  'id' : string,
  'creator' : string,
  'message' : string,
  'timestamp' : bigint,
  'position' : [number, number],
}
export interface _SERVICE {
  'addHeartNote' : ActorMethod<
    [string, string, string, bigint, [number, number]],
    boolean
  >,
  'deleteHeartNote' : ActorMethod<[string], undefined>,
  'editHeartNote' : ActorMethod<[string, string], undefined>,
  'getAllHeartNotes' : ActorMethod<[], Array<HeartNote>>,
  'getHeartNote' : ActorMethod<[string], HeartNote>,
  'getHeartNotesForUser' : ActorMethod<[string], Array<HeartNote>>,
  'getPersonalGreetingMessage' : ActorMethod<[], string>,
  'updatePersonalGreetingMessage' : ActorMethod<[string], undefined>,
  'updatePosition' : ActorMethod<[string, [number, number]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];